feat: added function to get content of a trendmark as string immediately
FraunhoferISST/Innamark pull request #108
Opened 2024-08-07 19:35 UTC by gemdav

## Description

This PR adds a convenience function to the Trendmark Interface that returns the content of the Trendmark as a string (instead of a byte list).

## Linked Issue(s)

Fixes #107 

## CLA
By submitting this pull request, I have read the [Corporate Contributor License Agreement (CLA)](https://github.com/FraunhoferISST/TREND/blob/main/CLA.md) and I hereby accept and sign the CLA.

2024-08-07 19:36 UTC, gemdav commented
@mhellmeier please review when you find the time

2024-08-12 10:03 UTC, mhellmeier requested changes

2024-08-12 10:03 UTC, mhellmeier commented on watermarker/src/commonMain/kotlin/watermarks/Trendmark.kt
> +    /** Returns the decoded information stored in the Trendmark as a string*/
```suggestion
    /** Returns the decoded information stored in the Trendmark as a String, if possible */
```

2024-08-12 10:03 UTC, mhellmeier commented on watermarker/src/commonMain/kotlin/watermarks/Trendmark.kt
Some notes and hints regarding this proposal:
- Currently, tests are missing for this implementation. Please add some unit tests in the correct file (`TrendmarkTest.kt`)
- The new function `getContentAsString()` is the only function that isn't overridden. It might make sense to add a function in the `sealed interface TrendmarkInterface` above
- The error handling needs to be extended. Most of the users use the library to watermark Strings inside a cover. But it is also possible that the watermark itself has a specific Byte format that is not a String. The function should handle those cases

2024-09-11 15:34 UTC, gemdav commented on watermarker/src/commonMain/kotlin/watermarks/Trendmark.kt
@mhellmeier The requested changes have now been implemented. Again, please review when you find the time.

2024-10-18 08:06 UTC, mhellmeier commented
I will close this PR as discussed in the upstream issue #108 because the generic `Trendmark` class should not focus on text-based watermarks only. As described in [this comment](https://github.com/FraunhoferISST/TREND/issues/107#issuecomment-2360577459), the `TextWatermark` class should be used for it.

The [problem of unsupported Trendmark types](https://github.com/FraunhoferISST/TREND/issues/107#issuecomment-2374389155) will be fixed in #134.

2024-10-18 08:06 UTC, closed without merging