feat(webinterface): add Trendmark advanced settings
FraunhoferISST/Innamark pull request #139
Opened 2024-10-30 11:54 UTC by mhellmeier

## Description

This pull request adds new checkboxes in the webinterface to support different types of Trendmarks.

## Linked Issue(s)

Fixes #103

## CLA
By submitting this pull request, I have read the [Corporate Contributor License Agreement (CLA)](https://github.com/FraunhoferISST/TREND/blob/main/CLA.md) and I hereby accept and sign the CLA.

2024-11-07 10:34 UTC, Schiphorst-ISST requested changes
LGTM just a few suggestions to improve user experience

2024-11-07 10:34 UTC, Schiphorst-ISST commented on webinterface/src/jsMain/kotlin/WatermarkTextEmbedTab.kt
The progress bar and the comment at the bottom of the page should update when any of the advanced options are selected as the space needed for the watermark increases. The watermarkFitsInText function needs to be updated to check the size needed for each type of watermark, currently only checks for default Watermarks. Additionally it should be considered if a watermark using both CRC32 and SHA3256 is planned in the future or if the webinterface should prevent users from selecting both checkboxes.

2024-11-11 07:49 UTC, eschrewe requested changes

2024-11-11 07:49 UTC, eschrewe commented on webinterface/src/jsMain/kotlin/WatermarkTextEmbedTab.kt
I agree with that statement.

2024-11-11 14:46 UTC, mhellmeier commented on webinterface/src/jsMain/kotlin/WatermarkTextEmbedTab.kt
The progress bar update now considers the selected options of the advanced settings. A selection of CRC32 and SHA3256 may be possible, but we shouldn't block this PR because the decision depends on the library, not the webinterface.

2024-11-12 07:27 UTC, eschrewe requested changes

2024-11-12 07:27 UTC, eschrewe commented on webinterface/src/jsMain/kotlin/WatermarkTextEmbedTab.kt
I think we need a similar line for the SHA3256CheckBox too

2024-11-19 08:01 UTC, eschrewe requested changes
Hi, I did some additional testing and found some unexpected behaviour, see below.

2024-11-19 08:01 UTC, eschrewe commented on webinterface/src/jsMain/kotlin/WatermarkTextEmbedTab.kt
Hi, 
I just did some testing. I used the watermark "a"  
and the covertext "a a a a a a a a a a"   



The progress bar tells me, that this exactly fits into the covertext. (None of the checkboxes are selected, so just it  should be the "raw" trendmark. But before doing that I randomly switched the checkboxes randomly on and off...)

Then i push the "Add Watermark" button and copy the output to the clipboard. 

But when I insert the content from the clipboard to the "Extract" section and click the "Extract Watermark" button, then I get a result message stating that no valid watermark could be found. 

But now I just inserted the clipboard content into the testbed-gui and extracted it with the Java RAW Trendmark algo. Surprisingly I got the expected hidded message there. 

Hmm...

2024-11-27 12:59 UTC, mhellmeier commented on webinterface/src/jsMain/kotlin/WatermarkTextEmbedTab.kt
Urgh, I replicated it.

The webinterface and the progress bar work as expected. After debugging the issue, the problem is rooted one level up in the watermarker library and does not relate to this PR. Therefore, it should not block this PR.

To keep the issue on track, I created a unit test and added a new bug report (see #159).

2024-11-27 15:00 UTC, eschrewe commented on webinterface/src/jsMain/kotlin/WatermarkTextEmbedTab.kt
Thank you very much!
Aside from that, I see no issues, so I'm giving "green light" for this PR ;)

2024-11-27 15:00 UTC, eschrewe approved these changes
LGTM, thank you very much!

2024-11-28 08:44 UTC, Schiphorst-ISST approved these changes
LGTM

2024-11-28 08:51 UTC, merged