docs: update contributing information
FraunhoferISST/Innamark pull request #43
Opened 2024-05-16 07:49 UTC by mhellmeier

## Description
This PR updates the `CONTRIBUTING.md` file by providing necessary information about our workflow, structure, and guidelines in order to better guide newcomers.

## Linked Issue(s)
Fixes #42 

## CLA
By submitting this pull request, I have read the [Corporate Contributor License Agreement (CLA)](https://github.com/FraunhoferISST/TREND/blob/main/CLA.md) and I hereby accept and sign the CLA.

2024-05-16 08:52 UTC, hqarawlus requested changes
LGTM, however, some minor changes are needed

2024-05-16 08:52 UTC, hqarawlus commented on CONTRIBUTING.md
> +the repository (if you haven't write permission). Create a branch with a descriptive name (like
```suggestion
the repository (if you do not have write permission). Create a branch with a descriptive name (like
```

2024-05-16 08:52 UTC, hqarawlus commented on CONTRIBUTING.md
> +request from your working branch to the upstream `main` branch, fill out the template, link it
```suggestion
request from your working branch or fork to the upstream `main` branch, fill out the template, link it 
```

2024-05-16 08:52 UTC, hqarawlus commented on CONTRIBUTING.md
> +Further note that every pull request has to be related to at least one issue. This guarantees
Already mentioned on line 44

2024-05-16 09:17 UTC, hnorkowski commented on CONTRIBUTING.md
> +<type>(<component>): <descriptive title>
we could recommend using [commitlint](https://github.com/conventional-changelog/commitlint)

2024-05-16 09:17 UTC, hnorkowski commented on CONTRIBUTING.md
> +Committer team. Further check that all pipelines succeed before requesting a review.
Can external users trigger our pipelines?

2024-05-16 09:17 UTC, hnorkowski commented on CONTRIBUTING.md
> +Remember that every method must contain a comment since it is used in the automatic
the combination of contain and just comment (not documentations comment) sound like you have to add a normal comment inside of the function body. We could link [this](https://kotlinlang.org/docs/kotlin-doc.html#kdoc-syntax).

2024-05-16 13:25 UTC, mhellmeier commented on CONTRIBUTING.md
> +Remember that every method must contain a comment since it is used in the automatic
Good point! Maybe we should also add a general hint that documentation and concepts should be updated.

2024-05-22 09:47 UTC, mhellmeier commented on CONTRIBUTING.md
> +Committer team. Further check that all pipelines succeed before requesting a review.
The pipelines should run on all pull requests, yes. But I will update the part to make it more clear.

2024-05-22 12:14 UTC, hnorkowski commented on CONTRIBUTING.md
> +Committer team. Further check that all pipelines succeed before requesting a review.
I was asking because of an open-source project where its required that a reviewer starts the pipeline. AFAIK its done that way to prevent DOS attacks and preventing exploiting any security vuln. in the pipelines.

2024-05-22 12:17 UTC, hnorkowski approved these changes
LGTM

2024-05-23 07:48 UTC, hqarawlus approved these changes

2024-05-23 07:50 UTC, merged